---
Name: s2hub-textassistant-config
After:
  - '*'
---
SilverStripe\Forms\FormField:
  extensions:
    - S2Hub\TextAssistant\Extensions\FormFieldExtension

SilverStripe\ORM\DataObject:
  extensions:
    - S2Hub\TextAssistant\Extensions\DataObjectTranslationActionExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - S2Hub\TextAssistant\Extensions\LeftAndMainExtension

TractorCow\Fluent\Model\Locale:
  extensions:
    - S2Hub\TextAssistant\Extensions\LocaleExtension

SilverStripe\Security\Member:
  extensions:
    - S2Hub\TextAssistant\Extensions\MemberExtension
